<?php

// $chattingModel =$this->getChattingData();
$chattingList = Mage::getModel('chatting/chatting')->getCollection();

?>
<div class="container" style="margin-top:20px;">
    <div class="table overflow-x-scroll">
        <table class="table table-striped">
            <tr>
                <th>Id</th>
                <th> From User Name</th>
                <th> To User Name</th>
                <th> Message</th>
            </tr>
            <tr>
                <?php
                foreach ($chattingList->getData() as $chat):

                    ?>
                    <td>
                        <?php echo $chat->getId(); ?>
                    </td>
                    <td>
                        <?php echo $chat->getFromUser(); ?>
                    </td>

                    <td>
                        <?php echo $chat->getToUser(); ?>
                    </td>
                    <td>
                        <?php echo $chat->getMessage(); ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tr>
        </table>