<?php

$id = $this->getRequest()->getParams('id', 0);
// echo $id;
$categoryData = Mage::getModel('catalog/product')->getCollection()->addFieldToFilter('category_id', "{$id}");

// print_r($categoryData->getData());die;

?>
</pre>

<div class="container mt-5">
    <div class="row">

        <!-- Product starts here -->
        <?php foreach ($categoryData->getData() as $category): ?>
            <div class="col-md-4 mb-4">
                <div class="card h-100">
                    <img src="<?php echo Mage::getBaseUrl() . 'media/product/' . $category->getImageLink(); ?>"
                        class="card-img-top" alt="Product Image" height="350"
                        style='border:1px solid grey;object-fit:contain'>
                    <div class="card-body">
                        <h5 class="card-title">
                            <?php echo $category->getName() ?>
                        </h5>
                         <p class="card-text"> 
                            <?php echo '₹' . $category->getPrice() ?>
                        </p> 
                        <!-- <button class="edit-button p-2"><a href='<?php //echo $this->getUrl('catalog/product/view') ?>?id=<?php //echo $category->getProductId() ?>'>View Details </a></button> -->
                        <button class="edit-button p-2"
                            style="background-color: #4CAF50; color: white; padding: 10px 20px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; margin: 4px 2px; cursor: pointer; border-radius: 8px; border: none; transition-duration: 0.4s;">
                            <a href="<?php echo $this->getUrl('catalog/product/view') ?>?id=<?php echo $category->getProductId(); ?>"
                                style="color: white; text-decoration: none;">View Details</a>
                        </button>

                    </div>
                </div>
            </div>
        <?php endforeach ?>
        <!-- Product ends here -->
    </div>
</div>