<?php
$bannerModel=Mage::getModel("banner/banner")->getCollection();
?>
<div id="carouselExampleCaptions" class="carousel slide carousel-fade carousel-dark mt-2 mb-2" data-bs-ride="carousel" style="width:90%;margin:auto">
    
    
    <div class="carousel-inner">
    <?php foreach($bannerModel->getData() as $banner):?>
      <div class="carousel-item <?php echo ($banner->getBannerId() == 2) ? 'active' : '' ;?>">
        <img src="<?php echo Mage::getBaseUrl().'media/banner/'.$banner->getBannerImage();?>" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5 class=><?php echo $banner->getTitle();?></h5>
          <p><?php echo $banner->getShowOn();?></p>
        </div>
      </div>
      <?php endforeach ?>
    </div>
    
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
