<?php
$orders = $this->getOrder()->getData();

// print_r($orders);die;
?>


<?php if (count($orders)): ?>
    <h2 style="margin-left:75px;margin-bottom:10px;">My Orders <i class="fa-solid fa-bag-shopping"></i></h2>
    <div class="container" style="margin-top:20px;">
        <div class="table overflow-x-scroll">
            <table class="table table-striped">
                <tr>
                    <th>Sr. No</th>
                    <th>Order Number</th>
                    <th>Grand Total</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
                <?php $i = 1; ?>
                <?php foreach ($orders as $order): ?>
                    <tr>
                        <td>
                            <?php echo $i; ?>
                        </td>
                        <td>
                            <?php echo $order->getOrderNumber(); ?>
                        </td>
                        <td>
                            <?php echo $order->getGrandTotal(); ?>
                        </td>
                        <td>
                            <?php echo $order->getStatus(); ?>
                        </td>

                        <td><a href='<?php echo $this->getUrl('sales/order/details') ?>?id=<?php echo $order->getOrderId(); ?>'><button
                                    class="btn btn-secondary">Order Details <i class="fa-solid fa-circle-info"
                                        style="color: #f9f7f1;"></i></button></a></td>
                    </tr>
                    <?php $i++; ?>
                <?php endforeach ?>
            </table>
        </div>
    </div>
<?php else: ?>
    <h1>No orders yet!</h1>
<?php endif ?>

