<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
<body> 
    <footer>
        <div class="footer-col">
            <h4>Quick Links</h4>
            <ul>
                <li><a href="<?php echo $this->getUrl('page/index/index');?>">Home</a></li>
                <li><a href="<?php echo $this->getUrl('catalog/product/view');?>">Shop</a></li>
                <li><a href="#">About</a></li>
            </ul>
        </div>
        <div class="footer-col">
            <h4>network</h4>
            <ul>
                <li><a href="#">technology</a></li>
                <li><a href="#">science</a></li>
                <li><a href="#">business</a></li>
                <li><a href="#">professional</a></li>
                <li><a href="#">API</a></li>
            </ul>
        </div>
        <div class="footer-col">
            <h4>company</h4>
            <ul>
                <li><a href="#">about</a></li>
                <li><a href="#">legal</a></li>
                <li><a href="#">contact us</a></li>
            </ul>
        </div>
        <div class="footer-col">
            <h4>follow us</h4>
            <div class="links">
                <a href="#"><i class="fab fa-linkedin-in"></i></a>
                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
            </div>
        </div>
    </footer>
</body>
</html> 
