<!-- <h2>Head</h2> -->
<link rel="stylesheet" href="<?php echo Mage::getBaseUrl() . 'skin/css/product/header.css' ?>">
<link rel="stylesheet" href="<?php echo Mage::getBaseUrl() . 'skin/css/product/footer.css' ?>">



<?php $js=$this->getJs(); ?>
<?php if(count($js)): ?>
    <?php foreach($js as $_js): ?>
        <script type="" src="<?php echo $_js?>"></script>
        <?php endforeach; ?>
<?php endif; ?>

<?php $css=$this->getCss(); ?>
<?php if(count($css)): ?>
    <?php foreach($css as $_css): ?>
        <link rel="stylesheet" href="<?php echo $_css?>">
        <?php endforeach; ?>
<?php endif; ?>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<!-- list bootstrap -->