    <header>
           <div class="logo">MarketHub</div>
           <nav>
                <ul>
                    <li><a href="#">home</a></li>
                    <li><a href="#">about</a></li>
                    <li><a href="#">contact</a></li>
                    <li><a href="#">services</a></li>
                </ul>
           </nav>

           <div class="button">
               <a href="#" class="btn btn-1">learn more</a>
               <a href="#" class="btn btn-2">book now</a>
           </div>
    </header>
