
    <?php
        // $id = $this->getRequest()->getParams('id');
        // echo $id;
        $product_model=$this->getProduct();
        // echo Mage::getSingleton('core/session')->remove('customerId');

        // print_r($product_model);

    ?>
    <form action="<?php echo $this->getUrl("admin/catalog_product/save");?>" enctype="multipart/form-data" method="post" class="product">

    <input type="hidden"  value="<?php echo $product_model->getId();?>"name="pdata[product_id]"  />

    <label for="sku">sku</label>
    <input type="text" id="sku" value="<?php echo $product_model->getSku();?>"name="pdata[sku]"  />

    <label for="productName">Product Name</label>
    <input type="text" id="productName" name="pdata[name]" value="<?php echo $product_model->getName();?>" />

    <label for="Color">Color</label>
    <input type="text" id="color" name="pdata[color]" value="<?php echo $product_model->getColor();?>" />

    <label for="size">size</label>
    <input type="text" id="size" name="pdata[size]" value="<?php echo $product_model->getSize();?>" />

    <label for="Description">Description</label>
    <textarea id="description" name="pdata[description]" value="<?php echo $product_model->getDescription();?>" cols="30" rows="10"></textarea>

    <label for="image link">Image Link</label>
    <input type="file" name="pdata[image_link]" value="<?php echo $product_model->getImageLink();?>"id="imageLink">

    <label for="link">Link</label>
    <input type="text" name="pdata[link]" value="<?php echo $product_model->getLink();?>"id="link">

    <label for="category">Category</label>
    <select name="pdata[category_id]" id="category_id">
    <option value="">--select--</option>
            <option value="1" <?php echo ($product_model->getCategoryId()) == 'Tops' ?'selected':'';?>>Tops</option>
            <option value="2" <?php echo ($product_model->getCategoryId()) == 'T-shirts' ?'selected':'';?>>T-shirts</option>
            <option value="3" <?php echo ($product_model->getCategoryId()) == 'Jeans' ?'selected':'';?>>Jeans</option>
            <option value="4" <?php echo ($product_model->getCategoryId()) == 'Shirts' ?'selected':'';?>>Shirts</option>
            <option value="5" <?php echo ($product_model->getCategoryId()) == 'Kurtas' ?'selected':'';?>>Kurtas</option>
            <option value="6" <?php echo ($product_model->getCategoryId()) == 'Chaniya Choli' ?'selected':'';?>>Chaniya Choli</option>
            <option value="7" <?php echo ($product_model->getCategoryId()) == 'Wedding Lahengas' ?'selected':'';?>>Wedding Lahengas</option>
            <option value="8" <?php echo ($product_model->getCategoryId()) == 'Ethnic Dresses' ?'selected':'';?>>Ethnic Dresses</option>
            <option value="9" <?php echo ($product_model->getCategoryId()) == 'Western Wear' ?'selected':'';?>>Western Wear</option>
            <option value="10" <?php echo ($product_model->getCategoryId()) == 'Trousers' ?'selected':'';?>>Trousers</option>
            <option value="11" <?php echo ($product_model->getCategoryId()) == 'Active Wear' ?'selected':'';?>>Active Wear</option>
            <option value="12" <?php echo ($product_model->getCategoryId()) == 'Formal Wear' ?'selected':'';?>>Formal Wear</option>
            <option value="13" <?php echo ($product_model->getCategoryId()) == 'Jump Suits' ?'selected':'';?>>Jump Suits</option>
            <option value="14" <?php echo ($product_model->getCategoryId()) == 'Party Wear' ?'selected':'';?>>Party Wear</option>
            <option value="15" <?php echo ($product_model->getCategoryId()) == 'Pajamas' ?'selected':'';?>>Pajamas</option>
    </select>

    <label for="price">Price</label>
    <input type="text" id="price" name="pdata[price]" value="<?php echo $product_model->getPrice();?>" />

    <label for="manufacturerCost">Manufacturer Cost</label>
    <input type="text" id="manufacturerCost" name="pdata[mfr_cost]" value="<?php echo $product_model->getMfrCost();?>" />

    <label for="shippingCost">Shipping Cost</label>
    <input type="text" id="shippingCost" name="pdata[shipping_cost]" value="<?php echo $product_model->getShippingCost();?>" />

    <label for="totalCost">Total Cost</label>
    <input type="text" id="totalCost" name="pdata[total_cost]" value="<?php echo $product_model->getTotalCost();?>" />

    <label for="margin percentage">Margin Percentage</label>
    <input type="text" id="marginPercentage" name="pdata[margin_percentage]" value="<?php echo $product_model->getMarginPercentage();?>" />

    <label for="min price">Min Price</label>
    <input type="text" id="minPrice" name="pdata[min_price]" value="<?php echo $product_model->getMinPrice();?>" />

    <label for="status">Status</label>
    <select name="pdata[status]" id="status">
        <option value="1"<?php echo ($product_model->getStatus() == "E")?'selected' : '' ;?>>enable</option>
        <option value="0"<?php echo ($product_model->getStatus() == "D")?'selected' : '' ;?>>disable</option>
    </select>

    <input type="submit" name="" value="submit" />
</form>

    
