<!-- <?php echo 23 ?> -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
        <!-- <div class="header"><?php  $this->getChild('header')->toHtml(); ?> </div> -->
        
        <div class="header"><?php  $this->getChildHtml('header')?> </div>
        <div class="Content">
        <div class="Content">Left</div>
        <div class="Content">content</div>
        <div class="Content">Right</div>

        </div>
        <div class="Footer"><?php $this->getChild('footer')?></div>
</body>
</html>
