<!-- list phtml content -->
<?php

$productList = Mage::getModel('catalog/product')->getCollection();
?>
<div class="container" style="margin-top:20px;">
    <div class="table"> 
        <table class="table table-striped overflow-x-auto">
            <tr>
                <th>Product Id</th>
                <th>SKU</th>
                <th>Product Name</th>
                <th>Color</th>
                <th>Size</th>
                <th>Description</th>
                <th>Image-Link</th>
                <th>Link</th>
                <th>Category Id</th>
                <th>Price</th>
                <th>mfr_cost</th>
                <th>Shipping Cost</th>
                <th>Total Cost</th>
                <th>Margin_Prcentage</th>
                <th>Min_Price</th>
                <th>Status</th>
                <th>View</th>
            </tr>
            <?php
            foreach($productList->getData() as $product)
            {
            ?>
            <tr>
                <td>
                    <?php print_r($product->getId());?>
                </td>
                <td>
                    <?php print_r($product->getSku()); ?>
                </td>
                <td>
                    <?php print_r($product->getName()); ?>
                </td>
                <td>
                    <?php print_r($product->getColor()); ?>
                </td>
                <td>
                    <?php print_r($product->getSize()); ?>
                </td>
                <td>
                    <?php print_r($product->getDescription()); ?>
                </td>
                <td>
                    <?php print_r($product->getImageLink()); ?>
                </td>
                <td>
                    <?php print_r($product->getLink()); ?>
                </td>
                <td>
                    <?php print_r($product->getCategoryId()); ?>
                </td>
                <td>
                    <?php print_r($product->getPrice()); ?>
                </td>
                <td>
                    <?php print_r($product->getMfrCost()); ?>
                </td>
                <td>
                    <?php print_r($product->getShippingCost()); ?>
                </td>
                <td>
                    <?php print_r($product->getTotalCost()); ?>
                </td>
                <td>
                    <?php print_r($product->getPrice()); ?>
                </td>
                <td>
                    <?php print_r($product->getMarginPercentage()); ?>
                </td>
                <td>
                    <?php print_r($product->getStatus()); ?>
                </td>
                <td>
                    <a href="<?php echo $this->getUrl('catalog/product/view?id=') . $product->getId() ?>"
                        class=""><button type="button" class="btn btn-outline-success">View</button></a>
                </td>
                
            </tr>
            <?php }  ?>
        </table>
    </div>
</div>