<?php $product = $this->getProduct() ?>
<div class="container">
  <div class="row mt-5">
    <div class="col-md-6">
      <img src="<?php echo Mage::getBaseUrl() . 'media/product/' . $product->getImageLink(); ?>" class="img-fluid"
        alt="Product Image">
    </div>
    <div class="col-md-6">
      <h2 class="product-title">
        <?php echo $product->getName() ?>
      </h2>

      <p><strong>Color:</strong>
        <?php echo $product->getColor() ?>
      </p>
      <p><strong>Category:</strong>
        <?php echo $product->getCategoryId() ?>
      </p>
      <p><strong>Description:</strong>
        <?php echo $product->getDescription() ?>
      </p>
      <p><strong>Price:</strong>
        <?php echo $product->getPrice() ?>
      </p>
      <div class="form-group">
        <form method="post" action="<?php echo $this->getUrl("sales/quote/add") ?>">
          <div class="col-md-6">

            <form action="<?php echo $this->getUrl('sales/quote/add?id=') . $product->getId() ?>" method="post">


              <div class="form-group">
                <input type="text" hidden name="qdata[product_id]" value="<?php echo $product->getProductId() ?>">

                <label for="quantity" style="font-size: 18px; color: #000000;">Select Quantity:</label>
                <input type="number" name=qdata[quantity] id="quantity" class="form-control" value="1" min="1">
              </div>
              <button type="submit" class="btn btn-success" style="margin-top: 10px;">Add To Cart</button>
            </form>
          </div>
      </div>

    </div>
  </div>
</div>