

    <div class="login-container" >
        <form action="" method="post" class="login-form" id="login-form">
            <h2>Login</h2>
            <div class="input-group">
                <label for="userid">User ID:</label>
                <input type="text" id="userid" name="cdata[customer_email]" required>
            </div>
            <div class="input-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="cdata[password]" required>
            </div>
            <!-- <button type="submit">Login</button> -->
            
            <button type="button" onclick="loginAction(this)" value="Login" class="">Login</button>
            <!-- <a href="<?php //echo $this->getUrl('customer/account/register')?>">New User,Register Here</a> -->
			<div id="message"></div>
        </form>
		
    </div>

	<script type="text/javascript">
	function loginAction(btn) {
		//console.log($('#login-form'));
		var form = $($('#login-form')[0]);
		console.log(form.serialize());
		$.ajax({
			url: form.action,
			type:'POST',
			// contentType: "application/json",
			data: form.serialize()	
		}).done(function(response) {
			var output = JSON.parse(response);
			// alert(response)
			alert(output.type)
			if(output.type=="success"){
				alert(output.message);
				window.location.href="<?php echo $this->getUrl('customer/account/dashboard');?>";
			}
			else{
				alert(output.message);
			}
			// $('#message')[0].innerHTML = output.message;
			// alert(output.message)
			// $( this ).addClass( "done" );
			// $( this ).addClass( "done" );
		});
	}
</script> 

    