<div class="login-container">
        <form action="" method="post" class="login-form">
            <h2>Admin Login</h2>
            <div class="input-group">
                <label for="userid">Admin ID:</label>
                <input type="text" id="userid" name="adata[admin_email]" required>
            </div>
            <div class="input-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="adata[admin_password]" required>
            </div>
            <button type="submit">Login</button>
            
            
            <!-- <a href="<?php //echo $this->getUrl('customer/account/register')?>">New User,Register Here</a> -->
        </form>
    </div>